// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const content: string;
export const title: string;
export const formContainer: string;
export const form: string;
